### ISSUE TITLE
WorldGen Fixing for 1.16.2

### ISSUE THREAD

**Issue by MatrexsVigil** [MatrexsVigil/phc2crops#17]
I need help fixing the init/WorldGenRegistry and all the garden block classes in the worldgen/ folder.

**Comment by Vlaeh** [comment]
Hi @MatrexsVigil ,
Are you still needing help fixing world generation ?

Pam's Harvest Craft mods are really great.
I had a look at branch 1.16.3, and it can work again with only few changes:
https://github.com/Vlaeh/phc2crops/commit/370837c655256d93d13e3dea1efe01ccef372dbd
I can create a pull request if you wish.
From the few tests I could make I noted an issue with tropical gardens, they are only generated in Beach and Ocean biomes ( GardenGeneration.java ) but as those biomes mostly contain sand instead of the required dirt/grass block they are not generated.

**Comment by MatrexsVigil** [comment]
No longer needed
